### ISSUE TITLE
webstorm debug 模式下 访问不到controll层，只有npm start运行才能正常访问到controll层.

### ISSUE THREAD

**Issue by dainixiao** [einsqing/koahubjs#2]
webstorm debug 模式下 访问不到controll层，只有npm start运行才能正常访问到controll层.   
for (var key in koahub.controllers) {
                    if (key == path) {
                        include = true;
                        break;
                    }
                }
koahub.controllers  数组为0

**Comment by einsqing** [comment]
controller是运行时自动加载的，所以npm start之后，可以log除koahub变量看下所有挂载的数据

**Comment by einsqing** [comment]
推荐你看下demo，https://github.com/einsqing/koahubjs-demo

**Comment by dainixiao** [comment]
就是运行的koahubjs-demo,但我用webstorm自带的run  和 debug去启动app/index.js 就访问不到控制器了。
或者有什么推荐的debug调试方式吗？

**Comment by einsqing** [comment]
那估计是你debug在控制器加载之前了，webstorm的bug很好用。

**Comment by einsqing** [comment]
@dainixiao 现在可以使用webstorm debug了，node debugger在cluster模式，或者多进程模式下，不可以使用debug。目前koahubjs使用了自己开发的cli工具启动的，如果需要debug，直接正常启动就可以了。
